### ISSUE TITLE
Google Prelaunch tests Reports implicit Intents

### ISSUE THREAD

**Issue by cirk2** [cyface-de/android-backend#237]
Message from app pre-launch report:

Implicit Internal Intent
Your app contains an Implicit Internal Intent vulnerability. Please see this [Google Help Center article](https://support.google.com/faqs/answer/10399926) for details.
    de.cyface.synchronization.CyfaceConnectionStatusListener.onProgress
    de.cyface.synchronization.CyfaceConnectionStatusListener.onSyncFinished
    de.cyface.synchronization.CyfaceConnectionStatusListener.onSyncStarted

This seems to be a new Validation Google performs since it newly apeard with the first builds in 2022 while still staying on Cyface SDK version 6.2.0

**Comment by hb0** [comment]
Hi, thanks for forwarding this report.

In our case this should not be a security issue as no sensitive information is sent though these intents - the intents are used to inform the UI about the sync progress, so even if a possible attacker changes or removes these intents, not much harm can be done here.

Therefore I'll close this issue, but if you think otherwise just let us know.
